import { BusinessProfile, Category, Product } from '../types';

export const DEFAULT_BUSINESS_PROFILE: BusinessProfile = {
  id: 'ayra-fashion',
  businessName: 'AYRA FASHION',
  businessType: 'All Types Clothing Store',
  logoUrl: '/logo.jpg',
  email: 'ayra.fashion.assam@gmail.com',
  whatsapp: '+91 91275 86750',
  contactNumber: '+91 60036 60069',
  catalogueSlug: 'ayra-fashion',
};

export const INITIAL_CATEGORIES: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  { id: 'cat-shirts', businessId: 'ayra-fashion', name: 'Shirts', slug: 'shirts', description: 'Formal, casual, and linen shirts for men' },
  { id: 'cat-sarees', businessId: 'ayra-fashion', name: 'Sarees', slug: 'sarees', description: 'Traditional silk, georgette, and designer sarees' },
  { id: 'cat-dresses', businessId: 'ayra-fashion', name: 'Dresses', slug: 'dresses', description: 'Casual, party wear, and ethnic dresses' },
  { id: 'cat-tshirts', businessId: 'ayra-fashion', name: 'T-Shirts', slug: 't-shirts', description: 'Round neck, polo, and printed graphic tees' },
  { id: 'cat-jeans', businessId: 'ayra-fashion', name: 'Jeans', slug: 'jeans', description: 'Slim fit, straight, and stretchable denim trousers' },
  { id: 'cat-men', businessId: 'ayra-fashion', name: 'Men', slug: 'men', description: 'Complete collection of menswear' },
  { id: 'cat-women', businessId: 'ayra-fashion', name: 'Women', slug: 'women', description: 'Western, ethnic, and daily wear for women' },
  { id: 'cat-kids', businessId: 'ayra-fashion', name: 'Kids', slug: 'kids', description: 'Comfortable & festive clothes for boys and girls' },
  { id: 'cat-accessories', businessId: 'ayra-fashion', name: 'Accessories', slug: 'accessories', description: 'Belts, dupattas, stoles, and fashion add-ons' },
];

export const INITIAL_PRODUCTS: Omit<Product, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'prod-1',
    businessId: 'ayra-fashion',
    name: 'Premium Cotton Shirt',
    price: 799,
    categoryId: 'cat-shirts',
    categoryName: 'Shirts',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    description: '100% breathable pure combed cotton casual shirt with spread collar and tailored fit. Ideal for office and daily casual wear.',
    availability: 'Available',
  },
  {
    id: 'prod-2',
    businessId: 'ayra-fashion',
    name: "Women's Floral Anarkali Dress",
    price: 1499,
    categoryId: 'cat-dresses',
    categoryName: 'Dresses',
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80',
    description: 'Flowy flared rayon Anarkali with intricate botanical floral prints and gold lace detailing on neckline.',
    availability: 'Available',
  },
  {
    id: 'prod-3',
    businessId: 'ayra-fashion',
    name: 'Classic Slim-Fit Denim Jeans',
    price: 1199,
    categoryId: 'cat-jeans',
    categoryName: 'Jeans',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
    description: 'Stretchable rugged indigo blue denim trousers with 5-pocket styling, durable brass rivets, and modern tapered leg.',
    availability: 'Available',
  },
  {
    id: 'prod-4',
    businessId: 'ayra-fashion',
    name: 'Designer Kanjivaram Silk Saree',
    price: 2999,
    categoryId: 'cat-sarees',
    categoryName: 'Sarees',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
    description: 'Traditional rich jacquard woven gold zari border saree in royal maroon with unstitched matching blouse piece.',
    availability: 'Available',
  },
  {
    id: 'prod-5',
    businessId: 'ayra-fashion',
    name: "Men's Casual Crew Neck T-Shirt",
    price: 449,
    categoryId: 'cat-tshirts',
    categoryName: 'T-Shirts',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    description: 'Supima cotton bio-washed solid charcoal grey round-neck tee. Ultra-soft feel, anti-pilling, and shrink-resistant.',
    availability: 'Available',
  },
  {
    id: 'prod-6',
    businessId: 'ayra-fashion',
    name: 'Kids Festive Jacquard Kurta Set',
    price: 899,
    categoryId: 'cat-kids',
    categoryName: 'Kids',
    imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80',
    description: 'Vibrant silk-blend ethnic kurta with comfortable churidar pyjama set for boys, perfect for festive celebrations.',
    availability: 'Available',
  },
  {
    id: 'prod-7',
    businessId: 'ayra-fashion',
    name: 'Embroidered Party Wear Georgette Kurti',
    price: 1299,
    categoryId: 'cat-women',
    categoryName: 'Women',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
    description: 'Pastel peach faux georgette tunic with fine thread and sequin embroidery on yolk and cuffs.',
    availability: 'Available',
  },
  {
    id: 'prod-8',
    businessId: 'ayra-fashion',
    name: 'Pure Leather Reversible Formal Belt',
    price: 599,
    categoryId: 'cat-accessories',
    categoryName: 'Accessories',
    imageUrl: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&auto=format&fit=crop&q=80',
    description: 'Top-grain genuine leather belt with dual-tone black & brown finish and 360-degree twist buckle.',
    availability: 'Available',
  },
  {
    id: 'prod-9',
    businessId: 'ayra-fashion',
    name: 'Breathable Olive Linen Shirt',
    price: 949,
    categoryId: 'cat-shirts',
    categoryName: 'Shirts',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    description: 'Lightweight pure French linen shirt with mandarin collar, ideal for summer comfort and subtle luxury.',
    availability: 'Out of Stock',
  },
];
